spring.application.name=clinic-management
spring.datasource.url=jdbc:sqlserver://ZAKIET24-DEVWEB:1433;databaseName=clinic_management;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=200614

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true